/*
 * Permission to use, copy, modify, and/or distribute this software
 * for any purpose with or without fee is hereby granted, provided
 * that the above copyright notice and this permission notice
 * appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 * WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define APP_BASE_ADDRESS (0x08000000 + BOOTLOADER_OFFSET)
#define FLASH_PAGE_SIZE  2048
#define DFU_UPLOAD_AVAILABLE 1
#define DFU_DOWNLOAD_AVAILABLE 1

#define HAVE_LED 1
#define LED_OPEN_DRAIN 0
#define LED_ACTIVE_HIGH 1
#define LED_GPIO_PORT GPIOC
#define LED_GPIO_PIN GPIO7

#define HAVE_BUTTON 1
#define BUTTON_ACTIVE_HIGH 0
#define BUTTON_GPIO_PORT GPIOA
#define BUTTON_GPIO_PIN GPIO3
#define BUTTON_USES_PULL 0

#define BUTTON_SAMPLE_DELAY_CYCLES 1440000

#define HAVE_USB_PULLUP_CONTROL 1
#define USB_PULLUP_GPIO_PORT GPIOA
#define USB_PULLUP_GPIO_PIN GPIO8
#define USB_PULLUP_ACTIVE_HIGH 0
#define USB_PULLUP_OPEN_DRAIN 1

#define USES_GPIOA 1
#define USES_GPIOC 1

#endif
